#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
picom &
$HOME/.config/picom.conf
$HOME/.config/polybar/launch.sh
kmonad ~/.config/tutorial.kbd

bspc monitor -d I II III IV V

bspc config border_width         1
bspc config window_gap          7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
#bspc config gapless_monocle      true
bspc config single_monocle	 true
bspc config ignore_ewmh_focus	 true

bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#6e6a86"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
